## 0. Quelques mots sur les environnements virtuels. 

**Qu'est-ce-qu'un environnement virtuel ?**


* *environnement virtuel* = espace isolé et autonome dans lequel vous pouvez installer des bibliothèques, des packages et des dépendances logicielles spécifiques à un projet sans affecter le système global de votre machine --> utile pour résoudre les problèmes de gestion des dépendances et garantir une isolation entre différents projets.

* *idée* = créer un espace de travail indépendant où vous pouvez installer les versions spécifiques de bibliothèques et d'outils nécessaires à votre projet, sans affecter le reste de votre système -> permet d'éviter les conflits de versions et assure que chaque projet peut fonctionner avec les dépendances exactes dont il a besoin.

**Avantages de conda dans un environnement virtuel ?**

1. *Gestion des dépendances* : Conda gère les dépendances de manière efficace, en installant les packages et en résolvant automatiquement les conflits. Cela simplifie la gestion des environnements et assure la compatibilité entre les packages.

2. *Environnements isolés* : Conda permet de créer des environnements virtuels isolés les uns des autres, ce qui signifie que les dépendances d'un projet n'interféreront pas avec celles d'un autre projet.

3. *Langages multiples* : Conda n'est pas spécifique à un langage de programmation particulier. Il peut être utilisé pour gérer les environnements virtuels pour des projets Python, R, Ruby, Lua, Scala, Java, JavaScript, C/C++, FORTRAN, et plus encore.

**Voici les commandes utilisées pour créer l'environnement virtuel**

- `git clone https://github.com/NailKhelifa/PyTorch_Personnal` : pour cloner ce repertoire

- `cd PyTorch_Personnal` : pour se diriger vers ce repertoire

- `conda create --name pytorch --file requirements.txt` : pour créer un environnement virtuel du nom de **pytorch**

- `conda list --export > requirements.txt` : pour mettre à jour requirements.txt

- `conda activate pytorch` : pour activer l'environnement virtuel 

- `conda list` : montre tous les packages et leur versions dans l'environnement virtuel

In [16]:
import torch
import numpy as np

## 1. Les tenseurs sur PyTorch

### 1.1. How to create a tensor 
* In PyTorch, everything is based on tensors operations. They are the equivalent arrays in NumPy. 

* Tensors can have multiple dimensions (1-D, 2-D, ...). To create an empty tensor use `torch.empty(size)` (for instance `torch.empty(1)` gives a scalar, `torch.empty(3)` gives a 1-D tensor with length 3, `torch.empty(2, 2, 2)` gives a 3-D tensor with length 2).

* Randomly initialized tensors with `torch.rand(size)`, tensors with ones `torch.ones(size)`, tensors with zero `torch.zeros(size)`

* We can specify the type of values in the tensor with `torch.rand(size, dtype=torch.int)`, `torch.rand(size, dtype=torch.float)`... 

* We can access the size of the tensor with `x.size` where `x` is a tensor

* We can create a tensor using a list `x = torch.tensor([2.5, 3])`


### 1.2. How to make operations on tensors

* We have element-wise operations using `z = x + y` or `z = torch.add(x, y)`

* Inplace operations 

In [5]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

## element-wise addiiton
z = x + y
z = torch.add(x, y)
y.add_(x) # inplace

## element-wise subtraction
z = x - y
z = torch.subtract(x, y)
y.sub_(x) # inplace

## element-wise multiplication
z = x * y 
z = torch.mul(x, y)
y.mul_(x) # inplace

## element-wise division
z = x / y
z = torch.div(x, y)
y.div_(x) # inplace


tensor([[0.4338, 0.5367],
        [0.7397, 0.4796]])

There are also slicing operations as with lists and arrays in NumPy

In [7]:
x = torch.rand(5, 3)
print(x[:, 0])
print(x[1, 1].item()) ## prints the value. Beware -> works only if oyu have one element in your tensor

tensor([0.4969, 0.1584, 0.7790, 0.9673, 0.0341])
0.9651920795440674


We can reshape tensors

In [ ]:
x = torch.rand(4, 4)
y = x.view(16) ## it changes the dimensions --> the number of elements must be the same
y = x.view(-1, 8) ## if we dont want to put the array in one dimension, we only specify the 
                  ## dimension of array and python will determine the rest (here 2 x 8)

How to convert from NumPy array to torch.tensor and the other way around

In [21]:
## from torch to numpy

a = torch.ones(6)
b = a.numpy() ## be careful with the parenthesis
 
## BE CAREFUL : if you work on the CPU and not the GPU, modifying b will also modify a because 
##              both objects share the same memory location

a.add_(1)
print(a, b) ## modifies both objects

## from numpy to torch 

a = np.ones(5)
b = torch.from_numpy(a)

a += 1
print(a, b)


tensor([2., 2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 2. Gradient Calculation With Autograd

We here focus on the autograd package in pytorch and how we can calculate gradients with it. Gradients are essential for our optimization problems and this is a very useful tool. 

Pytorch already includes all the tools required to compute gradients. 

Note the difference: 

* `torch.randn()`: generates random numbers from a uniform distribution between 0 (inclusive) and 1 (exclusive).

* `torch.rand()`: generates random numbers from a uniform distribution between 0 (inclusive) and 1 (exclusive).

In [26]:
x = torch.randn(3, requires_grad=True)

y = x + 2 

![Alt text](image.png)